### ISSUE TITLE
Playing MOV with alpha

### ISSUE THREAD

**Issue by barelief** [soyoungshin/ofxGstStandaloneVideo#1]
Tried to play transparent (Alpha) fullHD *.mov video (PNG compression) with both OF_PIXELS_BGRA and OF_PIXELS_RGBA, but both these formats give me exceptions. Is there any way to play videos with alpha?

**Comment by soyoungshin** [comment]
Hey, did you get this one figured out? The code here is pretty old (summer 2012), there was a thread on the openframeworks forums suggests a fix was added to the ofx gstreamer wrapper in 2013 for alpha support.

http://forum.openframeworks.cc/t/using-video-with-alpha-ofvideoplayer-linux-gstreamer/11307

Also, since the code is a bit old, you may be well served checking out outsidecontext's fork. it looks recent as of oct 13. https://github.com/outsidecontext/ofxGstStandaloneVideo

Lastly, unfortunately, I don't have a windows box to test on. But others have implemented the same solution for using gstreamer as a standalone within ofx. The original ofx thread may be of use to you. http://forum.openframeworks.cc/t/gstreamer-as-a-standalone-addon-for-windows-example/10900

lmk what you end up doing. I'm curious to see.

Cheers
Soyoung

**Comment by barelief** [comment]
Soyung, Thanks thanks for the tips. 
I've manged to compile it somehow, It plays those files (1080p), however I'm not satisfied with framerate and cpu load. So I'm trying different approach.

Cheers
.

**Comment by soyoungshin** [comment]
Great! Just an fyi, we ended up going Linux + Gstreamer + a beefy computer with SSD for the installation this was a part of. My memory is pretty hazy, but I think I recall we had a roughly 50% increase in performance moving to Linux from Windows, and we were showing 6 HD videos at a time.

Good luck!
